<!--
 * @Descripttion: 
 * @version: 
 * @Author: Addicated
 * @Date: 2020-11-16 17:32:07
 * @LastEditors: Addicated
 * @LastEditTime: 2020-11-16 18:49:37
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>自定义错误拦截</title>
</head>

<body>
    <h1>自动应以的错误拦截页面</h1>
    <!-- 下面这种方式出现错误之后可以直接从网页上点击查看源代码来进行查看是哪部分的代码出现了问题 -->
    <div>
        <div th:utext="'&lt;!--'" th:remove="tag"></div>
        <div th:utext="'Failed Request URL : ' + ${url}" th:remove="tag"></div>
        <div th:utext="'Exception message : ' + ${exception.message}" th:remove="tag"></div>
        <ul th:remove="tag">
            <li th:each="st : ${exception.stackTrace}" th:remove="tag"><span th:utext="${st}" th:remove="tag"></span>
            </li>
        </ul>
        <div th:utext="'--&gt;'" th:remove="tag"></div>
    </div>
</body>

</html>